# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: make
  displayName: '[step] make'

- script: make default
  displayName: '[step] execute'

- script: make clean
  displayName: '[step] make clean'
