# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: make
  displayName: '[step] make'

- script: |
   main.exe
   echo Exit Code:%errorlevel%
   exit errorlevel
  displayName: '[step] execute main()'
