# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    gcc --version
    make flash.c
    make logger.c
    make unittest.c
    make main
  displayName: '[step] gcc compilation'
